// Generated by schema_generator
// datastore: mongodb (Mongoose)
const mongoose = require('mongoose');
const { Schema } = mongoose;

// Single account record for all roles; role-specific profile data embedded as subdocuments
const UserSchema = new Schema({
  email: { type: String },
  phone: { type: String },
  passwordHash: { type: String, required: true },
  role: { type: String, required: true, enum: ["customer", "restaurantManager", "deliveryAgent", "platformAdmin"] },
  isVerified: { type: Boolean, required: true, default: false },
  verificationToken: { type: String },
  verificationTokenExpiresAt: { type: Date },
  passwordResetToken: { type: String },
  passwordResetExpiresAt: { type: Date },
  failedLoginAttempts: { type: Number, required: true, default: 0 },
  lockedUntil: { type: Date },
  status: { type: String, required: true, enum: ["active", "suspended", "pending"], default: "pending" },
  fullName: { type: String, required: true },
  avatarUrl: { type: String },
  savedAddresses: [{
    _id: { type: Schema.Types.ObjectId, required: true },
    label: { type: String },
    line1: { type: String, required: true },
    line2: { type: String },
    city: { type: String, required: true },
    postalCode: { type: String, required: true },
    country: { type: String, required: true },
    location: {
      type: { type: String, enum: ["Point"], default: "Point" },
      coordinates: [{ type: Number, required: true }]
    },
    isDefault: { type: Boolean, default: false }
  }],
  agentProfile: {
    isAvailable: { type: Boolean, default: false },
    vehicleType: { type: String },
    licencePlate: { type: String },
    currentLocation: {
      type: { type: String, enum: ["Point"], default: "Point" },
      coordinates: [{ type: Number, required: true }]
    },
    locationUpdatedAt: { type: Date }
  },
  managerProfile: {
    restaurantId: { type: Schema.Types.ObjectId, ref: 'Restaurant' }
  },
  pushTokens: [{ type: String }],
  notificationPreferences: { type: Schema.Types.Mixed }
}, { timestamps: true });
UserSchema.index({ email: 1 }, { unique: true, sparse: true });
UserSchema.index({ phone: 1 }, { unique: true, sparse: true });
UserSchema.index({ role: 1 });
UserSchema.index({ status: 1 });
UserSchema.index({ verificationToken: 1 }, { sparse: true });
UserSchema.index({ passwordResetToken: 1 }, { sparse: true });
UserSchema.index({ 'agentProfile.currentLocation': '2dsphere' }, { sparse: true });
const User = mongoose.model('User', UserSchema);

// Restaurant partner profile with embedded menu categories and menu items as the primary browse/discovery document
const RestaurantSchema = new Schema({
  name: { type: String, required: true },
  slug: { type: String, required: true, unique: true },
  description: { type: String },
  cuisineTypes: [{ type: String, required: true }],
  logoUrl: { type: String },
  bannerUrl: { type: String },
  managerId: { type: Schema.Types.ObjectId, ref: 'User', required: true },
  status: { type: String, required: true, enum: ["active", "suspended", "pending"], default: "pending" },
  isOpen: { type: Boolean, required: true, default: false },
  address: {
    line1: { type: String, required: true },
    line2: { type: String },
    city: { type: String, required: true },
    postalCode: { type: String, required: true },
    country: { type: String, required: true },
    location: {
      type: { type: String, enum: ["Point"], default: "Point" },
      coordinates: [{ type: Number, required: true }]
    }
  },
  deliveryRadiusKm: { type: Number, required: true, default: 5 },
  deliveryFee: { type: Schema.Types.Decimal128, required: true },
  minimumOrderValue: { type: Schema.Types.Decimal128, required: true },
  estimatedDeliveryMinutes: { type: Number, required: true },
  avgRating: { type: Number, default: 0 },
  reviewCount: { type: Number, default: 0 },
  allowsCashOnDelivery: { type: Boolean, default: false },
  operatingHours: [{
    dayOfWeek: { type: Number, required: true },
    openTime: { type: String, required: true },
    closeTime: { type: String, required: true }
  }],
  menuCategories: [{
    _id: { type: Schema.Types.ObjectId, required: true },
    name: { type: String, required: true },
    description: { type: String },
    sortOrder: { type: Number, default: 0 },
    isAvailable: { type: Boolean, default: true },
    items: [{
      _id: { type: Schema.Types.ObjectId, required: true },
      name: { type: String, required: true },
      description: { type: String },
      price: { type: Schema.Types.Decimal128, required: true },
      imageUrl: { type: String },
      isAvailable: { type: Boolean, default: true },
      sortOrder: { type: Number, default: 0 },
      tags: [{ type: String }],
      allergens: [{ type: String }]
    }]
  }],
  commissionRate: { type: Number },
  onboardedAt: { type: Date },
  suspendedAt: { type: Date },
  suspensionReason: { type: String }
}, { timestamps: true });
RestaurantSchema.index({ slug: 1 }, { unique: true });
RestaurantSchema.index({ managerId: 1 });
RestaurantSchema.index({ status: 1 });
RestaurantSchema.index({ cuisineTypes: 1 });
RestaurantSchema.index({ isOpen: 1 });
RestaurantSchema.index({ avgRating: 1 });
RestaurantSchema.index({ 'address.location': '2dsphere' });
RestaurantSchema.index({ name: 'text', cuisineTypes: 'text' });
const Restaurant = mongoose.model('Restaurant', RestaurantSchema);

// Transient per-customer per-restaurant cart; TTL expiry after prolonged inactivity
const CartSchema = new Schema({
  customerId: { type: Schema.Types.ObjectId, ref: 'User', required: true },
  restaurantId: { type: Schema.Types.ObjectId, ref: 'Restaurant', required: true },
  items: [{
    menuItemId: { type: Schema.Types.ObjectId, required: true },
    name: { type: String, required: true },
    unitPrice: { type: Schema.Types.Decimal128, required: true },
    quantity: { type: Number, required: true },
    imageUrl: { type: String },
    specialInstructions: { type: String }
  }],
  subtotal: { type: Schema.Types.Decimal128, required: true, default: 0 },
  deliveryFeeSnapshot: { type: Schema.Types.Decimal128 },
  taxAmount: { type: Schema.Types.Decimal128 },
  total: { type: Schema.Types.Decimal128 },
  fulfillmentType: { type: String, enum: ["delivery", "pickup"], default: "delivery" },
  deliveryAddressId: { type: Schema.Types.ObjectId },
  lastActivityAt: { type: Date, required: true }
}, { timestamps: true });
CartSchema.index({ customerId: 1, restaurantId: 1 }, { unique: true });
CartSchema.index({ customerId: 1 });
CartSchema.index({ lastActivityAt: 1 }, { expireAfterSeconds: 259200 });
const Cart = mongoose.model('Cart', CartSchema);

// Confirmed order aggregate with snapshotted items, pricing, delivery address, and status history
const OrderSchema = new Schema({
  orderNumber: { type: String, required: true, unique: true },
  customerId: { type: Schema.Types.ObjectId, ref: 'User', required: true },
  restaurantId: { type: Schema.Types.ObjectId, ref: 'Restaurant', required: true },
  restaurantNameSnapshot: { type: String, required: true },
  items: [{
    menuItemId: { type: Schema.Types.ObjectId, required: true },
    name: { type: String, required: true },
    unitPrice: { type: Schema.Types.Decimal128, required: true },
    quantity: { type: Number, required: true },
    lineTotal: { type: Schema.Types.Decimal128, required: true },
    specialInstructions: { type: String }
  }],
  subtotal: { type: Schema.Types.Decimal128, required: true },
  deliveryFee: { type: Schema.Types.Decimal128, required: true },
  taxAmount: { type: Schema.Types.Decimal128, required: true },
  total: { type: Schema.Types.Decimal128, required: true },
  commissionAmount: { type: Schema.Types.Decimal128 },
  fulfillmentType: { type: String, required: true, enum: ["delivery", "pickup"] },
  deliveryAddress: {
    line1: { type: String, required: true },
    line2: { type: String },
    city: { type: String, required: true },
    postalCode: { type: String, required: true },
    country: { type: String, required: true },
    location: {
      type: { type: String, enum: ["Point"], default: "Point" },
      coordinates: [{ type: Number, required: true }]
    }
  },
  status: { type: String, required: true, enum: ["pendingRestaurantAcceptance", "accepted", "preparing", "ready", "outForDelivery", "delivered", "cancelledByCustomer", "cancelledByRestaurant", "cancelledByAdmin"] },
  statusHistory: [{
    status: { type: String, required: true },
    occurredAt: { type: Date, required: true },
    note: { type: String }
  }],
  rejectionReason: { type: String },
  cancellationReason: { type: String },
  paymentId: { type: Schema.Types.ObjectId, ref: 'Payment' },
  deliveryId: { type: Schema.Types.ObjectId, ref: 'Delivery' },
  reviewId: { type: Schema.Types.ObjectId, ref: 'Review' },
  restaurantAcceptedAt: { type: Date },
  readyAt: { type: Date },
  deliveredAt: { type: Date },
  estimatedDeliveryTime: { type: Date },
  specialInstructions: { type: String }
}, { timestamps: true });
OrderSchema.index({ orderNumber: 1 }, { unique: true });
OrderSchema.index({ customerId: 1, status: 1 });
OrderSchema.index({ restaurantId: 1, status: 1 });
OrderSchema.index({ status: 1 });
OrderSchema.index({ paymentId: 1 });
OrderSchema.index({ deliveryId: 1 });
const Order = mongoose.model('Order', OrderSchema);

// Payment gateway transaction record per order; no raw card data stored
const PaymentSchema = new Schema({
  orderId: { type: Schema.Types.ObjectId, ref: 'Order', required: true },
  customerId: { type: Schema.Types.ObjectId, ref: 'User', required: true },
  method: { type: String, required: true, enum: ["card", "digitalWallet", "cashOnDelivery"] },
  status: { type: String, required: true, enum: ["pending", "authorized", "captured", "failed", "refunded", "partiallyRefunded", "voided"] },
  amount: { type: Schema.Types.Decimal128, required: true },
  currency: { type: String, required: true, default: "USD" },
  gatewayTransactionRef: { type: String },
  gatewayPaymentToken: { type: String },
  gatewayResponseCode: { type: String },
  authorizedAt: { type: Date },
  capturedAt: { type: Date },
  refunds: [{
    _id: { type: Schema.Types.ObjectId, required: true },
    amount: { type: Schema.Types.Decimal128, required: true },
    reason: { type: String, required: true },
    gatewayRefundRef: { type: String },
    initiatedBy: { type: Schema.Types.ObjectId, ref: 'User' },
    refundedAt: { type: Date, required: true }
  }]
}, { timestamps: true });
PaymentSchema.index({ orderId: 1 }, { unique: true });
PaymentSchema.index({ customerId: 1 });
PaymentSchema.index({ status: 1 });
PaymentSchema.index({ gatewayTransactionRef: 1 }, { sparse: true });
const Payment = mongoose.model('Payment', PaymentSchema);

// Delivery lifecycle record per order; decoupled from order for independent agent-location write scaling
const DeliverySchema = new Schema({
  orderId: { type: Schema.Types.ObjectId, ref: 'Order', required: true },
  restaurantId: { type: Schema.Types.ObjectId, ref: 'Restaurant', required: true },
  agentId: { type: Schema.Types.ObjectId, ref: 'User' },
  status: { type: String, required: true, enum: ["unassigned", "offered", "agentAccepted", "agentDeclined", "pickedUp", "delivered", "failed"], default: "unassigned" },
  restaurantLocation: {
    type: { type: String, enum: ["Point"], default: "Point" },
    coordinates: [{ type: Number, required: true }]
  },
  deliveryLocation: {
    type: { type: String, enum: ["Point"], default: "Point" },
    coordinates: [{ type: Number, required: true }]
  },
  agentLiveLocation: {
    type: { type: String, enum: ["Point"], default: "Point" },
    coordinates: [{ type: Number, required: true }]
  },
  agentLocationUpdatedAt: { type: Date },
  estimatedArrivalAt: { type: Date },
  offeredAt: { type: Date },
  offerExpiresAt: { type: Date },
  acceptedAt: { type: Date },
  pickedUpAt: { type: Date },
  deliveredAt: { type: Date },
  proofOfDeliveryUrl: { type: String },
  assignmentAttempts: { type: Number, default: 0 },
  declinedByAgents: [{
    agentId: { type: Schema.Types.ObjectId, ref: 'User', required: true },
    declinedAt: { type: Date, required: true }
  }]
}, { timestamps: true });
DeliverySchema.index({ orderId: 1 }, { unique: true });
DeliverySchema.index({ agentId: 1, status: 1 });
DeliverySchema.index({ status: 1 });
DeliverySchema.index({ restaurantLocation: '2dsphere' });
DeliverySchema.index({ agentLiveLocation: '2dsphere' });
const Delivery = mongoose.model('Delivery', DeliverySchema);

// One customer review per delivered order; triggers denormalised avgRating update on Restaurant
const ReviewSchema = new Schema({
  orderId: { type: Schema.Types.ObjectId, ref: 'Order', required: true },
  restaurantId: { type: Schema.Types.ObjectId, ref: 'Restaurant', required: true },
  customerId: { type: Schema.Types.ObjectId, ref: 'User', required: true },
  rating: { type: Number, required: true },
  comment: { type: String },
  isVisible: { type: Boolean, required: true, default: true },
  removedByAdminId: { type: Schema.Types.ObjectId, ref: 'User' },
  removedAt: { type: Date },
  removalReason: { type: String }
}, { timestamps: true });
ReviewSchema.index({ orderId: 1 }, { unique: true });
ReviewSchema.index({ restaurantId: 1, isVisible: 1 });
ReviewSchema.index({ customerId: 1 });
ReviewSchema.index({ rating: 1 });
const Review = mongoose.model('Review', ReviewSchema);

// Singleton-style admin-managed platform configuration parameters
const PlatformConfigSchema = new Schema({
  key: { type: String, required: true, unique: true },
  value: { type: Schema.Types.Mixed, required: true },
  description: { type: String },
  lastUpdatedBy: { type: Schema.Types.ObjectId, ref: 'User' }
}, { timestamps: true });
PlatformConfigSchema.index({ key: 1 }, { unique: true });
const PlatformConfig = mongoose.model('PlatformConfig', PlatformConfigSchema);

// Immutable log of privileged administrative actions per REQ-40 / RBAC requirements
const AdminAuditLogSchema = new Schema({
  adminId: { type: Schema.Types.ObjectId, ref: 'User', required: true },
  action: { type: String, required: true },
  entityType: { type: String, required: true },
  entityId: { type: Schema.Types.ObjectId, required: true },
  before: { type: Schema.Types.Mixed },
  after: { type: Schema.Types.Mixed },
  ipAddress: { type: String },
  occurredAt: { type: Date, required: true }
}, { timestamps: true });
AdminAuditLogSchema.index({ adminId: 1 });
AdminAuditLogSchema.index({ entityType: 1, entityId: 1 });
AdminAuditLogSchema.index({ occurredAt: 1 });
const AdminAuditLog = mongoose.model('AdminAuditLog', AdminAuditLogSchema);

module.exports = { User, Restaurant, Cart, Order, Payment, Delivery, Review, PlatformConfig, AdminAuditLog };