// Generated by schema_generator
// datastore: mongodb (Mongoose)
const mongoose = require('mongoose');
const { Schema } = mongoose;

// Single collection for all four roles; role-specific sub-fields are conditional on the role field
const UserSchema = new Schema({
  email: { type: String },
  phone: { type: String },
  passwordHash: { type: String, required: true },
  role: { type: String, required: true, enum: ["customer", "restaurantManager", "deliveryAgent", "platformAdmin"] },
  firstName: { type: String, required: true },
  lastName: { type: String, required: true },
  avatarUrl: { type: String },
  isVerified: { type: Boolean, required: true, default: false },
  verificationToken: { type: String },
  verificationTokenExpiresAt: { type: Date },
  passwordResetToken: { type: String },
  passwordResetExpiresAt: { type: Date },
  failedLoginAttempts: { type: Number, required: true, default: 0 },
  lockedUntil: { type: Date },
  status: { type: String, required: true, enum: ["active", "suspended", "pendingVerification"], default: "pendingVerification" },
  savedAddresses: [{
    _id: { type: Schema.Types.ObjectId },
    label: { type: String },
    line1: { type: String, required: true },
    line2: { type: String },
    city: { type: String, required: true },
    postalCode: { type: String, required: true },
    country: { type: String, required: true },
    location: {
      type: { type: String, enum: ["Point"], default: "Point" },
      coordinates: [{ type: Number, required: true }]
    },
    isDefault: { type: Boolean, default: false }
  }],
  restaurantRef: { type: Schema.Types.ObjectId, ref: 'Restaurant' },
  agentProfile: {
    vehicleType: { type: String },
    licencePlate: { type: String },
    isAvailable: { type: Boolean, default: false },
    currentLocation: {
      type: { type: String, enum: ["Point"], default: "Point" },
      coordinates: [{ type: Number }]
    },
    activeDeliveryCount: { type: Number, default: 0 }
  },
  pushToken: { type: String },
  notificationPreferences: {
    push: { type: Boolean, default: true },
    sms: { type: Boolean, default: true },
    email: { type: Boolean, default: true }
  }
}, { timestamps: true });
UserSchema.index({ email: 1 }, { unique: true, sparse: true });
UserSchema.index({ phone: 1 }, { unique: true, sparse: true });
UserSchema.index({ role: 1 });
UserSchema.index({ status: 1 });
UserSchema.index({ verificationToken: 1 }, { sparse: true });
UserSchema.index({ passwordResetToken: 1 }, { sparse: true });
UserSchema.index({ restaurantRef: 1 }, { sparse: true });
UserSchema.index({ 'agentProfile.currentLocation': '2dsphere' }, { sparse: true });
const User = mongoose.model('User', UserSchema);

// Restaurant aggregate with fully embedded menu categories and items to serve the primary customer browsing read path
const RestaurantSchema = new Schema({
  name: { type: String, required: true },
  description: { type: String },
  cuisineTypes: [{ type: String, required: true }],
  logoUrl: { type: String },
  bannerUrl: { type: String },
  ownerRef: { type: Schema.Types.ObjectId, ref: 'User', required: true },
  status: { type: String, required: true, enum: ["active", "suspended", "pendingApproval", "inactive"], default: "pendingApproval" },
  isOpen: { type: Boolean, required: true, default: false },
  address: {
    line1: { type: String, required: true },
    line2: { type: String },
    city: { type: String, required: true },
    postalCode: { type: String, required: true },
    country: { type: String, required: true }
  },
  location: {
    type: { type: String, enum: ["Point"], default: "Point" },
    coordinates: [{ type: Number, required: true }]
  },
  deliveryRadiusKm: { type: Number, required: true, default: 5 },
  deliveryFee: { type: Schema.Types.Decimal128, required: true },
  minimumOrderValue: { type: Schema.Types.Decimal128, required: true },
  estimatedDeliveryTimeMinutes: { type: Number, required: true },
  averageRating: { type: Number, default: 0 },
  totalReviews: { type: Number, default: 0 },
  isCodAllowed: { type: Boolean, required: true, default: false },
  commissionRate: { type: Number },
  operatingHours: [{
    dayOfWeek: { type: Number, required: true },
    openTime: { type: String, required: true },
    closeTime: { type: String, required: true }
  }],
  menuCategories: [{
    _id: { type: Schema.Types.ObjectId },
    name: { type: String, required: true },
    description: { type: String },
    sortOrder: { type: Number, default: 0 },
    isAvailable: { type: Boolean, default: true },
    items: [{
      _id: { type: Schema.Types.ObjectId },
      name: { type: String, required: true },
      description: { type: String },
      price: { type: Schema.Types.Decimal128, required: true },
      imageUrl: { type: String },
      isAvailable: { type: Boolean, required: true, default: true },
      tags: [{ type: String }],
      sortOrder: { type: Number, default: 0 }
    }]
  }]
}, { timestamps: true });
RestaurantSchema.index({ location: '2dsphere' });
RestaurantSchema.index({ status: 1 });
RestaurantSchema.index({ isOpen: 1 });
RestaurantSchema.index({ cuisineTypes: 1 });
RestaurantSchema.index({ averageRating: 1 });
RestaurantSchema.index({ minimumOrderValue: 1 });
RestaurantSchema.index({ estimatedDeliveryTimeMinutes: 1 });
RestaurantSchema.index({ ownerRef: 1 });
RestaurantSchema.index({ name: 'text' });
const Restaurant = mongoose.model('Restaurant', RestaurantSchema);

// One active cart per customer per restaurant; transient, replaced on checkout
const CartSchema = new Schema({
  customerRef: { type: Schema.Types.ObjectId, ref: 'User', required: true },
  restaurantRef: { type: Schema.Types.ObjectId, ref: 'Restaurant', required: true },
  fulfillmentType: { type: String, enum: ["delivery", "pickup"], default: "delivery" },
  deliveryAddressId: { type: Schema.Types.ObjectId },
  items: [{
    menuItemId: { type: Schema.Types.ObjectId, required: true },
    categoryId: { type: Schema.Types.ObjectId, required: true },
    name: { type: String, required: true },
    unitPrice: { type: Schema.Types.Decimal128, required: true },
    quantity: { type: Number, required: true }
  }],
  subtotal: { type: Schema.Types.Decimal128 },
  taxAmount: { type: Schema.Types.Decimal128 },
  deliveryFee: { type: Schema.Types.Decimal128 },
  total: { type: Schema.Types.Decimal128 },
  expiresAt: { type: Date }
}, { timestamps: true });
CartSchema.index({ customerRef: 1, restaurantRef: 1 }, { unique: true });
CartSchema.index({ customerRef: 1 });
CartSchema.index({ expiresAt: 1 }, { expireAfterSeconds: 0 });
const Cart = mongoose.model('Cart', CartSchema);

// Immutable order record with price snapshot of items, bounded status history, and fulfilment details
const OrderSchema = new Schema({
  orderNumber: { type: String, required: true, unique: true },
  customerRef: { type: Schema.Types.ObjectId, ref: 'User', required: true },
  restaurantRef: { type: Schema.Types.ObjectId, ref: 'Restaurant', required: true },
  restaurantName: { type: String, required: true },
  status: { type: String, required: true, enum: ["pendingRestaurantAcceptance", "accepted", "preparing", "ready", "outForDelivery", "delivered", "cancelledByCustomer", "cancelledByRestaurant", "cancelledByAdmin"], default: "pendingRestaurantAcceptance" },
  fulfillmentType: { type: String, required: true, enum: ["delivery", "pickup"] },
  deliveryAddress: {
    line1: { type: String },
    line2: { type: String },
    city: { type: String },
    postalCode: { type: String },
    country: { type: String },
    location: {
      type: { type: String, enum: ["Point"] },
      coordinates: [{ type: Number }]
    }
  },
  items: [{
    menuItemId: { type: Schema.Types.ObjectId, required: true },
    categoryId: { type: Schema.Types.ObjectId, required: true },
    name: { type: String, required: true },
    unitPrice: { type: Schema.Types.Decimal128, required: true },
    quantity: { type: Number, required: true },
    lineTotal: { type: Schema.Types.Decimal128, required: true }
  }],
  subtotal: { type: Schema.Types.Decimal128, required: true },
  taxAmount: { type: Schema.Types.Decimal128, required: true },
  deliveryFee: { type: Schema.Types.Decimal128, required: true },
  serviceFee: { type: Schema.Types.Decimal128, required: true },
  total: { type: Schema.Types.Decimal128, required: true },
  commissionRate: { type: Number, required: true },
  commissionAmount: { type: Schema.Types.Decimal128, required: true },
  settlementAmount: { type: Schema.Types.Decimal128, required: true },
  paymentRef: { type: Schema.Types.ObjectId, ref: 'Payment' },
  deliveryRef: { type: Schema.Types.ObjectId, ref: 'Delivery' },
  reviewRef: { type: Schema.Types.ObjectId, ref: 'Review' },
  hasReview: { type: Boolean, required: true, default: false },
  cancellationReason: { type: String },
  cancellationCharged: { type: Boolean, default: false },
  rejectionReason: { type: String },
  acceptedAt: { type: Date },
  preparedAt: { type: Date },
  readyAt: { type: Date },
  deliveredAt: { type: Date },
  statusHistory: [{
    status: { type: String, required: true },
    changedAt: { type: Date, required: true },
    changedByRef: { type: Schema.Types.ObjectId, ref: 'User' },
    note: { type: String }
  }]
}, { timestamps: true });
OrderSchema.index({ orderNumber: 1 }, { unique: true });
OrderSchema.index({ customerRef: 1, status: 1 });
OrderSchema.index({ restaurantRef: 1, status: 1 });
OrderSchema.index({ paymentRef: 1 });
OrderSchema.index({ deliveryRef: 1 });
OrderSchema.index({ status: 1 });
OrderSchema.index({ createdAt: -1 });
const Order = mongoose.model('Order', OrderSchema);

// Isolated payment and refund lifecycle record; no raw card data stored per PCI DSS
const PaymentSchema = new Schema({
  orderRef: { type: Schema.Types.ObjectId, ref: 'Order', required: true },
  customerRef: { type: Schema.Types.ObjectId, ref: 'User', required: true },
  amount: { type: Schema.Types.Decimal128, required: true },
  currency: { type: String, required: true, default: "USD" },
  method: { type: String, required: true, enum: ["card", "digitalWallet", "cashOnDelivery"] },
  status: { type: String, required: true, enum: ["pending", "authorized", "captured", "failed", "refunded", "partiallyRefunded", "voided"], default: "pending" },
  gatewayTransactionId: { type: String },
  gatewayPaymentToken: { type: String },
  gatewayResponse: { type: Schema.Types.Mixed },
  authorizedAt: { type: Date },
  capturedAt: { type: Date },
  refunds: [{
    refundId: { type: String, required: true },
    amount: { type: Schema.Types.Decimal128, required: true },
    reason: { type: String },
    issuedByRef: { type: Schema.Types.ObjectId, ref: 'User' },
    gatewayRefundId: { type: String },
    status: { type: String, enum: ["pending", "succeeded", "failed"] },
    issuedAt: { type: Date, required: true }
  }],
  isCodCollected: { type: Boolean, default: false }
}, { timestamps: true });
PaymentSchema.index({ orderRef: 1 }, { unique: true });
PaymentSchema.index({ customerRef: 1 });
PaymentSchema.index({ gatewayTransactionId: 1 }, { sparse: true });
PaymentSchema.index({ status: 1 });
const Payment = mongoose.model('Payment', PaymentSchema);

// Tracks agent assignment, live location, reassignment attempts, ETA, and proof of delivery for each delivery order
const DeliverySchema = new Schema({
  orderRef: { type: Schema.Types.ObjectId, ref: 'Order', required: true },
  restaurantRef: { type: Schema.Types.ObjectId, ref: 'Restaurant', required: true },
  customerRef: { type: Schema.Types.ObjectId, ref: 'User', required: true },
  agentRef: { type: Schema.Types.ObjectId, ref: 'User' },
  status: { type: String, required: true, enum: ["awaitingAgent", "agentOffered", "agentAccepted", "agentDeclined", "pickedUp", "outForDelivery", "delivered", "failed", "cancelled"], default: "awaitingAgent" },
  restaurantLocation: {
    type: { type: String, enum: ["Point"] },
    coordinates: [{ type: Number }]
  },
  deliveryLocation: {
    type: { type: String, enum: ["Point"] },
    coordinates: [{ type: Number }]
  },
  agentCurrentLocation: {
    type: { type: String, enum: ["Point"] },
    coordinates: [{ type: Number }]
  },
  agentLocationUpdatedAt: { type: Date },
  estimatedArrivalAt: { type: Date },
  offeredAt: { type: Date },
  offerExpiresAt: { type: Date },
  acceptedAt: { type: Date },
  pickedUpAt: { type: Date },
  deliveredAt: { type: Date },
  proofOfDeliveryUrl: { type: String },
  assignmentAttempts: [{
    agentRef: { type: Schema.Types.ObjectId, ref: 'User', required: true },
    offeredAt: { type: Date, required: true },
    outcome: { type: String, required: true, enum: ["accepted", "declined", "timedOut"] },
    respondedAt: { type: Date }
  }]
}, { timestamps: true });
DeliverySchema.index({ orderRef: 1 }, { unique: true });
DeliverySchema.index({ agentRef: 1, status: 1 });
DeliverySchema.index({ status: 1 });
DeliverySchema.index({ agentCurrentLocation: '2dsphere' }, { sparse: true });
const Delivery = mongoose.model('Delivery', DeliverySchema);

// One review per delivered order; supports admin moderation and running-average recomputation
const ReviewSchema = new Schema({
  orderRef: { type: Schema.Types.ObjectId, ref: 'Order', required: true, unique: true },
  customerRef: { type: Schema.Types.ObjectId, ref: 'User', required: true },
  restaurantRef: { type: Schema.Types.ObjectId, ref: 'Restaurant', required: true },
  rating: { type: Number, required: true },
  comment: { type: String },
  status: { type: String, required: true, enum: ["published", "removedByAdmin"], default: "published" },
  removedByRef: { type: Schema.Types.ObjectId, ref: 'User' },
  removedAt: { type: Date },
  removalReason: { type: String }
}, { timestamps: true });
ReviewSchema.index({ orderRef: 1 }, { unique: true });
ReviewSchema.index({ restaurantRef: 1, status: 1 });
ReviewSchema.index({ customerRef: 1 });
ReviewSchema.index({ status: 1 });
const Review = mongoose.model('Review', ReviewSchema);

// Customer dispute records that administrators review and resolve, potentially triggering refunds
const DisputeSchema = new Schema({
  orderRef: { type: Schema.Types.ObjectId, ref: 'Order', required: true },
  customerRef: { type: Schema.Types.ObjectId, ref: 'User', required: true },
  restaurantRef: { type: Schema.Types.ObjectId, ref: 'Restaurant', required: true },
  description: { type: String, required: true },
  status: { type: String, required: true, enum: ["open", "underReview", "resolvedRefunded", "resolvedNoAction", "closed"], default: "open" },
  assignedAdminRef: { type: Schema.Types.ObjectId, ref: 'User' },
  resolutionNote: { type: String },
  refundIssued: { type: Boolean, default: false },
  refundAmount: { type: Schema.Types.Decimal128 },
  resolvedAt: { type: Date },
  resolvedByRef: { type: Schema.Types.ObjectId, ref: 'User' }
}, { timestamps: true });
DisputeSchema.index({ orderRef: 1 });
DisputeSchema.index({ customerRef: 1 });
DisputeSchema.index({ status: 1 });
DisputeSchema.index({ assignedAdminRef: 1 }, { sparse: true });
const Dispute = mongoose.model('Dispute', DisputeSchema);

// Singleton-style document holding administrator-configurable platform parameters (REQ-42)
const PlatformConfigSchema = new Schema({
  key: { type: String, required: true, unique: true },
  defaultCommissionRate: { type: Number },
  serviceFee: { type: Schema.Types.Decimal128 },
  defaultDeliveryRadiusKm: { type: Number },
  sessionTokenTtlSeconds: { type: Number },
  accountLockDurationSeconds: { type: Number },
  agentOfferTimeoutSeconds: { type: Number },
  cancellationChargePct: { type: Number },
  maxFailedLoginAttempts: { type: Number, default: 5 },
  updatedByRef: { type: Schema.Types.ObjectId, ref: 'User' }
}, { timestamps: true });
PlatformConfigSchema.index({ key: 1 }, { unique: true });
const PlatformConfig = mongoose.model('PlatformConfig', PlatformConfigSchema);

// Immutable log of every privileged administrative action for compliance and accountability
const AdminAuditLogSchema = new Schema({
  actorRef: { type: Schema.Types.ObjectId, ref: 'User', required: true },
  action: { type: String, required: true },
  targetCollection: { type: String, required: true },
  targetId: { type: Schema.Types.ObjectId, required: true },
  previousValue: { type: Schema.Types.Mixed },
  newValue: { type: Schema.Types.Mixed },
  ipAddress: { type: String },
  userAgent: { type: String }
}, { timestamps: true });
AdminAuditLogSchema.index({ actorRef: 1 });
AdminAuditLogSchema.index({ targetCollection: 1, targetId: 1 });
AdminAuditLogSchema.index({ createdAt: -1 });
const AdminAuditLog = mongoose.model('AdminAuditLog', AdminAuditLogSchema);

module.exports = { User, Restaurant, Cart, Order, Payment, Delivery, Review, Dispute, PlatformConfig, AdminAuditLog };