// Generated by schema_generator
// datastore: mongodb (Mongoose)
const mongoose = require('mongoose');
const { Schema } = mongoose;

// Single unified auth identity for all roles; role-specific profile data lives in its own collection referencing this document
const UserSchema = new Schema({
  email: { type: String, unique: true },
  phone: { type: String, unique: true },
  passwordHash: { type: String, required: true },
  role: { type: String, required: true, enum: ["customer", "restaurantManager", "deliveryAgent", "admin"] },
  isVerified: { type: Boolean, required: true, default: False },
  verificationToken: { type: String },
  verificationTokenExpiry: { type: Date },
  passwordResetToken: { type: String },
  passwordResetExpiry: { type: Date },
  failedLoginAttempts: { type: Number, required: true, default: 0 },
  lockedUntil: { type: Date },
  isActive: { type: Boolean, required: true, default: True },
  fullName: { type: String, required: true },
  avatarUrl: { type: String }
}, { timestamps: true });
UserSchema.index({ email: 1 }, { unique: true });
UserSchema.index({ phone: 1 }, { unique: true });
UserSchema.index({ role: 1 });
UserSchema.index({ passwordResetToken: 1 });
const User = mongoose.model('User', UserSchema);

// Customer-specific profile extending User; holds saved delivery addresses
const CustomerSchema = new Schema({
  userId: { type: Schema.Types.ObjectId, ref: 'User', required: true, unique: true },
  savedAddresses: [{
    _id: { type: Schema.Types.ObjectId },
    label: { type: String },
    line1: { type: String, required: true },
    line2: { type: String },
    city: { type: String, required: true },
    postcode: { type: String, required: true },
    coordinates: {
      lat: { type: Number, required: true },
      lng: { type: Number, required: true }
    },
    isDefault: { type: Boolean, default: False }
  }],
  preferredPaymentMethod: { type: String, enum: ["card", "wallet", "cod"] }
}, { timestamps: true });
CustomerSchema.index({ userId: 1 }, { unique: true });
const Customer = mongoose.model('Customer', CustomerSchema);

// Restaurant-manager-specific profile; links a user to one restaurant
const RestaurantManagerSchema = new Schema({
  userId: { type: Schema.Types.ObjectId, ref: 'User', required: true, unique: true },
  restaurantId: { type: Schema.Types.ObjectId, ref: 'Restaurant', required: true }
}, { timestamps: true });
RestaurantManagerSchema.index({ userId: 1 }, { unique: true });
RestaurantManagerSchema.index({ restaurantId: 1 });
const RestaurantManager = mongoose.model('RestaurantManager', RestaurantManagerSchema);

// Delivery-agent-specific profile with live availability and location state
const DeliveryAgentSchema = new Schema({
  userId: { type: Schema.Types.ObjectId, ref: 'User', required: true, unique: true },
  status: { type: String, required: true, enum: ["offline", "available", "busy"], default: "offline" },
  isApproved: { type: Boolean, required: true, default: False },
  isSuspended: { type: Boolean, required: true, default: False },
  currentLocation: {
    lat: { type: Number },
    lng: { type: Number },
    updatedAt: { type: Date }
  },
  vehicleType: { type: String, enum: ["bicycle", "motorcycle", "car"] },
  activeDeliveryId: { type: Schema.Types.ObjectId, ref: 'Delivery' }
}, { timestamps: true });
DeliveryAgentSchema.index({ userId: 1 }, { unique: true });
DeliveryAgentSchema.index({ status: 1 });
DeliveryAgentSchema.index({ currentLocation.lat: 1, currentLocation.lng: 1 });
const DeliveryAgent = mongoose.model('DeliveryAgent', DeliveryAgentSchema);

// Restaurant aggregate root; embeds full menu hierarchy (categories → items) for single-fetch browsing
const RestaurantSchema = new Schema({
  name: { type: String, required: true },
  description: { type: String },
  cuisineTypes: [{ type: String, required: true }],
  logoUrl: { type: String },
  bannerUrl: { type: String },
  address: {
    line1: { type: String, required: true },
    line2: { type: String },
    city: { type: String, required: true },
    postcode: { type: String, required: true },
    coordinates: {
      lat: { type: Number, required: true },
      lng: { type: Number, required: true }
    }
  },
  phone: { type: String },
  isOpen: { type: Boolean, required: true, default: False },
  isApproved: { type: Boolean, required: true, default: False },
  isSuspended: { type: Boolean, required: true, default: False },
  operatingHours: [{
    dayOfWeek: { type: Number, required: true },
    openTime: { type: String, required: true },
    closeTime: { type: String, required: true }
  }],
  deliveryRadiusKm: { type: Number, required: true },
  deliveryFee: { type: Schema.Types.Decimal128, required: true },
  minimumOrderValue: { type: Schema.Types.Decimal128, required: true },
  estimatedDeliveryMinutes: { type: Number, required: true },
  allowsCOD: { type: Boolean, required: true, default: False },
  avgRating: { type: Number, default: 0 },
  reviewCount: { type: Number, default: 0 },
  commissionRate: { type: Number },
  menuCategories: [{
    _id: { type: Schema.Types.ObjectId },
    name: { type: String, required: true },
    description: { type: String },
    sortOrder: { type: Number, default: 0 },
    isActive: { type: Boolean, default: True },
    items: [{
      _id: { type: Schema.Types.ObjectId },
      name: { type: String, required: true },
      description: { type: String },
      price: { type: Schema.Types.Decimal128, required: true },
      imageUrl: { type: String },
      isAvailable: { type: Boolean, required: true, default: True },
      sortOrder: { type: Number, default: 0 },
      tags: [{ type: String }]
    }]
  }]
}, { timestamps: true });
RestaurantSchema.index({ isApproved: 1, isSuspended: 1, isOpen: 1 });
RestaurantSchema.index({ cuisineTypes: 1 });
RestaurantSchema.index({ avgRating: 1 });
RestaurantSchema.index({ estimatedDeliveryMinutes: 1 });
RestaurantSchema.index({ address.coordinates.lat: 1, address.coordinates.lng: 1 });
RestaurantSchema.index({ name: 1 });
const Restaurant = mongoose.model('Restaurant', RestaurantSchema);

// One active cart per customer per restaurant; cleared on order placement or explicit abandon
const CartSchema = new Schema({
  customerId: { type: Schema.Types.ObjectId, ref: 'Customer', required: true },
  restaurantId: { type: Schema.Types.ObjectId, ref: 'Restaurant', required: true },
  items: [{
    menuItemId: { type: Schema.Types.ObjectId, required: true },
    name: { type: String, required: true },
    price: { type: Schema.Types.Decimal128, required: true },
    quantity: { type: Number, required: true },
    imageUrl: { type: String }
  }],
  subtotal: { type: Schema.Types.Decimal128, required: true },
  deliveryFeeSnapshot: { type: Schema.Types.Decimal128 },
  taxAmount: { type: Schema.Types.Decimal128 },
  total: { type: Schema.Types.Decimal128 },
  fulfillmentType: { type: String, enum: ["delivery", "pickup"], default: "delivery" },
  deliveryAddressId: { type: Schema.Types.ObjectId }
}, { timestamps: true });
CartSchema.index({ customerId: 1, restaurantId: 1 }, { unique: true });
CartSchema.index({ customerId: 1 });
const Cart = mongoose.model('Cart', CartSchema);

// Placed-order aggregate root; snapshots item names and prices for financial integrity; references Restaurant, Customer, and Agent
const OrderSchema = new Schema({
  customerId: { type: Schema.Types.ObjectId, ref: 'Customer', required: true },
  restaurantId: { type: Schema.Types.ObjectId, ref: 'Restaurant', required: true },
  restaurantName: { type: String, required: true },
  status: { type: String, required: true, enum: ["pendingRestaurantAcceptance", "accepted", "preparing", "ready", "outForDelivery", "delivered", "cancelledByCustomer", "cancelledByRestaurant", "cancelledByAdmin"], default: "pendingRestaurantAcceptance" },
  fulfillmentType: { type: String, required: true, enum: ["delivery", "pickup"] },
  deliveryAddress: {
    line1: { type: String, required: true },
    line2: { type: String },
    city: { type: String, required: true },
    postcode: { type: String, required: true },
    coordinates: {
      lat: { type: Number },
      lng: { type: Number }
    }
  },
  items: [{
    menuItemId: { type: Schema.Types.ObjectId, required: true },
    name: { type: String, required: true },
    unitPrice: { type: Schema.Types.Decimal128, required: true },
    quantity: { type: Number, required: true },
    lineTotal: { type: Schema.Types.Decimal128, required: true }
  }],
  subtotal: { type: Schema.Types.Decimal128, required: true },
  deliveryFee: { type: Schema.Types.Decimal128, required: true },
  taxAmount: { type: Schema.Types.Decimal128, required: true },
  total: { type: Schema.Types.Decimal128, required: true },
  commissionAmount: { type: Schema.Types.Decimal128 },
  rejectionReason: { type: String },
  cancellationReason: { type: String },
  deliveryAgentId: { type: Schema.Types.ObjectId, ref: 'DeliveryAgent' },
  statusHistory: [{
    status: { type: String, required: true },
    changedAt: { type: Date, required: true },
    changedBy: { type: Schema.Types.ObjectId, ref: 'User' }
  }],
  estimatedDeliveryMinutes: { type: Number },
  placedAt: { type: Date, required: true },
  acceptedAt: { type: Date },
  deliveredAt: { type: Date }
}, { timestamps: true });
OrderSchema.index({ customerId: 1, placedAt: 1 });
OrderSchema.index({ restaurantId: 1, status: 1 });
OrderSchema.index({ restaurantId: 1, placedAt: 1 });
OrderSchema.index({ deliveryAgentId: 1, status: 1 });
OrderSchema.index({ status: 1 });
OrderSchema.index({ placedAt: 1 });
const Order = mongoose.model('Order', OrderSchema);

// One payment record per order; stores gateway reference and tokenized method details only — no raw card data
const PaymentSchema = new Schema({
  orderId: { type: Schema.Types.ObjectId, ref: 'Order', required: true, unique: true },
  customerId: { type: Schema.Types.ObjectId, ref: 'Customer', required: true },
  method: { type: String, required: true, enum: ["card", "wallet", "cod"] },
  status: { type: String, required: true, enum: ["pending", "authorized", "captured", "failed", "refunded", "partiallyRefunded", "voided"], default: "pending" },
  amount: { type: Schema.Types.Decimal128, required: true },
  currency: { type: String, required: true, default: "GBP" },
  gatewayTransactionId: { type: String },
  gatewayPaymentToken: { type: String },
  gatewayResponse: { type: Schema.Types.Mixed },
  refunds: [{
    amount: { type: Schema.Types.Decimal128, required: true },
    reason: { type: String },
    gatewayRefundId: { type: String },
    initiatedBy: { type: Schema.Types.ObjectId, ref: 'User' },
    processedAt: { type: Date }
  }],
  paidAt: { type: Date }
}, { timestamps: true });
PaymentSchema.index({ orderId: 1 }, { unique: true });
PaymentSchema.index({ customerId: 1 });
PaymentSchema.index({ gatewayTransactionId: 1 });
PaymentSchema.index({ status: 1 });
const Payment = mongoose.model('Payment', PaymentSchema);

// Delivery lifecycle for one order; tracks agent assignment, live location snapshots, status, and proof-of-delivery
const DeliverySchema = new Schema({
  orderId: { type: Schema.Types.ObjectId, ref: 'Order', required: true, unique: true },
  restaurantId: { type: Schema.Types.ObjectId, ref: 'Restaurant', required: true },
  customerId: { type: Schema.Types.ObjectId, ref: 'Customer', required: true },
  deliveryAgentId: { type: Schema.Types.ObjectId, ref: 'DeliveryAgent' },
  status: { type: String, required: true, enum: ["unassigned", "offered", "assigned", "pickedUp", "delivered", "failed", "cancelled"], default: "unassigned" },
  offerExpiresAt: { type: Date },
  assignmentAttempts: [{
    agentId: { type: Schema.Types.ObjectId, ref: 'DeliveryAgent' },
    offeredAt: { type: Date },
    outcome: { type: String, enum: ["accepted", "declined", "timeout"] }
  }],
  pickupAddress: {
    line1: { type: String },
    city: { type: String },
    coordinates: {
      lat: { type: Number },
      lng: { type: Number }
    }
  },
  dropoffAddress: {
    line1: { type: String },
    city: { type: String },
    coordinates: {
      lat: { type: Number },
      lng: { type: Number }
    }
  },
  estimatedPickupAt: { type: Date },
  estimatedDropoffAt: { type: Date },
  actualPickedUpAt: { type: Date },
  actualDeliveredAt: { type: Date },
  proofOfDeliveryUrl: { type: String },
  agentLocationHistory: [{
    lat: { type: Number },
    lng: { type: Number },
    recordedAt: { type: Date }
  }]
}, { timestamps: true });
DeliverySchema.index({ orderId: 1 }, { unique: true });
DeliverySchema.index({ deliveryAgentId: 1, status: 1 });
DeliverySchema.index({ status: 1 });
DeliverySchema.index({ restaurantId: 1 });
const Delivery = mongoose.model('Delivery', DeliverySchema);

// One customer review per delivered order; used to recompute restaurant avgRating
const ReviewSchema = new Schema({
  orderId: { type: Schema.Types.ObjectId, ref: 'Order', required: true, unique: true },
  customerId: { type: Schema.Types.ObjectId, ref: 'Customer', required: true },
  restaurantId: { type: Schema.Types.ObjectId, ref: 'Restaurant', required: true },
  rating: { type: Number, required: true },
  comment: { type: String },
  isVisible: { type: Boolean, required: true, default: True },
  removedBy: { type: Schema.Types.ObjectId, ref: 'User' },
  removedAt: { type: Date },
  removalReason: { type: String }
}, { timestamps: true });
ReviewSchema.index({ orderId: 1 }, { unique: true });
ReviewSchema.index({ restaurantId: 1, isVisible: 1 });
ReviewSchema.index({ customerId: 1 });
const Review = mongoose.model('Review', ReviewSchema);

// Singleton-style admin-controlled configuration document for platform-wide parameters
const PlatformConfigSchema = new Schema({
  key: { type: String, required: true, unique: true },
  value: { type: Schema.Types.Mixed, required: true },
  description: { type: String },
  updatedBy: { type: Schema.Types.ObjectId, ref: 'User' }
}, { timestamps: true });
PlatformConfigSchema.index({ key: 1 }, { unique: true });
const PlatformConfig = mongoose.model('PlatformConfig', PlatformConfigSchema);

module.exports = { User, Customer, RestaurantManager, DeliveryAgent, Restaurant, Cart, Order, Payment, Delivery, Review, PlatformConfig };